version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: gwz sales
        
        tests:
          - unique:
              column_name: "(orders_id, '-', pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: gwz products and purchase price
        columns:
          - name: products_id
            description: product id
            tests:
              - not_null
              - unique
          - name: purchase_price
            description: price per product id
      - name: ship
        identifier: raw_gz_ship
        description: shipping fee, log and costs per order
        columns:
          - name: orders_id
            description: id per order
            tests:
              - not_null
              - unique
          - name: shipping_fee
            description: shipping fee per order
          - name: logCost
            description: logistics cost per order
          - name: ship_cost
            description: shipping cost
      - name: adwords
        identifier: raw_gz_adwords
        description: adwords mktg campaign
        columns:
          - name: date_date
            description: date of the ad
          - name: paid_source
            description: source of ad
          - name: campaign_key
            description: id of campaign
          - name: camPGN_name
            description: name of campaign      
          - name: ads_cost
            description: cost of ad
          - name: impression
            description: nb of impressions of ad
          - name: click
            description: nb of clicks of ad
      - name: bing
        identifier: raw_gz_bing
        description: bing mktg campaign
        columns:
          - name: date_date
            description: date of the ad
          - name: paid_source
            description: source of ad
          - name: campaign_key
            description: id of campaign
          - name: camPGN_name
            description: name of campaign      
          - name: ads_cost
            description: cost of ad
          - name: impression
            description: nb of impressions of ad
          - name: click
            description: nb of clicks of ad      
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo mktg campaign
        columns:
          - name: date_date
            description: date of the ad
          - name: paid_source
            description: source of ad
          - name: campaign_key
            description: id of campaign
          - name: camPGN_name
            description: name of campaign      
          - name: ads_cost
            description: cost of ad
          - name: impression
            description: nb of impressions of ad
          - name: click
            description: nb of clicks of ad        
      - name: facebook 
        identifier: raw_gz_facebook
        description: facebook mktg campaign
        columns:
          - name: date_date
            description: date of the ad
          - name: paid_source
            description: source of ad
          - name: campaign_key
            description: id of campaign
          - name: camPGN_name
            description: name of campaign      
          - name: ads_cost
            description: cost of ad
          - name: impression
            description: nb of impressions of ad
          - name: click
            description: nb of clicks of ad        
models:
  - name: int_orders_margin
    description: margin calculation per order
    columns:
      - name: orders_id
        description: orders key
        tests:
          - unique
          - not_null
  - name: int_orders_operational
    description: margin operational per order
    columns:
      - name: orders_id
        description: orders key
        tests:
          - not_null
          - unique
  - name: int_sales_margin
    description: margin per order
    columns:
      - name: orders_id
        description: orders key
        tests:
          - not_null  
      - name: date_date
        description: date of the order
        tests:
          - not_null
      - name: products_id
        description: product key
        tests:
          - not_null
      - name: margin
        description: margin = revenue - purchase cost
        tests:
          - not_null
      - name: quantity
        description: items in order
        tests:
          - not_null
    tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"
  - name: finance_days
    description: finance metrics
    columns:
      - name: date_date
        description: date of the transactions
        tests:
          - unique
          - not_null
  - name: int_campaigns
    description: union of four ads campaigns
    columns:
      - name: paid_source
        description: name of source of ad
        tests:
          - not_null
      - name: campaign_key
      - name: campaign_name
      - name: ads_cost
      - name: impression
      - name: click
    tests:
      - unique:
          column_name: "(date_date || '-' || campaign_key)"
  - name: int_campaigns_day
    description: aggreated by day
    columns:
      - name: date_date
        description: date of the ad
        tests:
          - not_null
          - unique
  - name: finance_campaign_day
    description: finance data with the ads margin
    columns: 
      - name: date_date
        tests:
          - not_null